---
- name: Converge
  hosts: all
  gather_facts: false
  #become: true
  tasks:
    - name: Do the thing
      filedrop:
      # tulloh.filedrop.filedrop:
    #- name: Second call
      #filedrop:
      #
      # TODO: Should verify the ouput too, maybe try playing with the changed/unchanged
