---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Fetch directory tree
      # Trying to dump the full tree from root doesn't work well, dev files etc.
      # So we go a little selective
      ansible.builtin.find:
        paths: "{{ item.path }}"
        recurse: "{{ item.recurse }}"
        file_type: "any"  # Include directories and links
        hidden: true  # Include hidden files
      register: find_res
      loop:
        - { path: "/", recurse: False }
        - { path: "/etc", recurse: True }
        - { path: "/dumped", recurse: True }
        #- { path: "/etc/profile.d", recurse: True }
        #- { path: "/etc/issue.d", recurse: True }

    #- name: Dump
      #ansible.builtin.debug:
        #var: find_res

    #- name: Dump2
      #ansible.builtin.debug:
        #msg: "{{ find_res.results | map(attribute='files') | flatten }}"

    - name: Set up file tree for lookups
      ansible.builtin.set_fact:
        tree: "{{ dict(files | map(attribute='path') | zip(files)) }}"
      vars:
        files: "{{ find_res.results | map(attribute='files') | flatten }}"

    #- name: Dump
    #  ansible.builtin.debug:
    #    var: tree
    - name: Dump
      ansible.builtin.debug:
        msg: "{{ tree | list }}"

    # File details are as per the stat module
    # /smithy": {"atime": 1745542108.6770728, "ctime": 1745542045.7403781, "dev": 132, "gid": 0, "gr_name": "root", "inode": 97020399, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0644", "mtime": 1745542043.0, "nlink": 1, "path": "/smithy", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 8, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}


    - name: Test expected files
      ansible.builtin.assert:
        that:
          - ("/rootfile" in tree)
          - ("/etc/bob" in tree)
          - ("/etc/bob/smith" in tree)
          - ("/etc/bob/smithy" in tree)
          # pw_name is the owner
          - tree["/dumped/d1/f1"]["pw_name"] == "games"
          - tree["/dumped/d2/f1"]["pw_name"] == "nobody"
          - tree["/dumped/d3/f1"]["pw_name"] == "sync"
          - tree["/dumped/d1/f1"]["gr_name"] == "dialout"
          - tree["/dumped/d2/f1"]["gr_name"] == "video"
          - tree["/dumped/d3/f1"]["gr_name"] == "tape"
          - tree["/dumped/d1/t1"]["pw_name"] == "lp"
          - tree["/dumped/d2/t1"]["pw_name"] == "bin"
          - tree["/dumped/d3/t1"]["pw_name"] == "sync"
          - tree["/dumped/d1/t1"]["gr_name"] == "games"
          - tree["/dumped/d2/t1"]["gr_name"] == "tty"
          - tree["/dumped/d3/t1"]["gr_name"] == "tape"
          # Default ignore pattern, don't transfer .keep or _keep
          # But d2 contains [._]keep.j2, which does get transfered to become [._]keep
          - ("/dumped/d1/.keep" not in tree)
          - ("/dumped/d1/_keep" not in tree)
          - ("/dumped/d2/.keep" in tree)
          - ("/dumped/d2/_keep" in tree)
          # Inherit from mail/kmem from directory, with overwrites
          - tree["/dumped/d5/f1"]["pw_name"] == "games"
          - tree["/dumped/d5/f1"]["gr_name"] == "dialout"
          - tree["/dumped/d5/p1"]["pw_name"] == "mail"
          - tree["/dumped/d5/p1"]["gr_name"] == "kmem"
          - tree["/dumped/d5/p2"]["pw_name"] == "games"
          - tree["/dumped/d5/p2"]["gr_name"] == "tty"
          - tree["/dumped/d5/p3"]["pw_name"] == "mail"
          - tree["/dumped/d5/p3"]["gr_name"] == "kmem"


    - name: Get file contents
      ansible.builtin.slurp:
        src: "{{ item }}"
      loop:
        - /etc/bob/smith
        - /etc/bob/smithy
      register: slurped

    #- name: Dump
    #  ansible.builtin.debug:
    #    var: slurped

    - name: Set up contents for lookups
      ansible.builtin.set_fact:
        contents_b64: "{{ slurped.results | items2dict(key_name='source', value_name='content') }}"

    - name: Test file contents
      ansible.builtin.assert:
        that:
          - contents_b64['/etc/bob/smith'] | b64decode == "SMITH\n"
          - contents_b64['/etc/bob/smithy'] | b64decode == "olympus\n"  # TODO: Dynamic
          # ansible_hostname and ansible_facts['nodename'] are both remote system, could do a local setup
          # Probably better to switch variable
